
{{- $root := .Values -}}
{{- $release := .Release -}}
{{- range $user := $root.users }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $user.name }}-password
type: Opaque
stringData:
  password: {{ $user.password }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $root.adminUser }}-password
type: Opaque
stringData:
  password: {{ $root.adminPassword }}