apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-database
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: allow-secrets
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: allow-secrets-to-mongodb-database-sa
subjects:
- kind: ServiceAccount
  name: mongodb-database
roleRef:
 kind: Role
 name:  allow-secrets
 apiGroup: rbac.authorization.k8s.io

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: allow-get-pods
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: allow-get-pods-to-mongodb-database-sa
subjects:
- kind: ServiceAccount
  name: mongodb-database
roleRef:
 kind: Role
 name:  allow-get-pods
 apiGroup: rbac.authorization.k8s.io