---
default:
  replicaCount: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi



deploys:

  - name: My Super App
    image:
      repository: nginx
      pullPolicy: IfNotPresent
      tag: ""

    imagePullSecrets: []

    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

    replicaCount: 1
    autoscaling:
      minReplicas: 1
      maxReplicas: 100
      targetCPUUtilizationPercentage: 80

    service:
      type: ClusterIP
      port: 80

    ingress:
      enabled: false
      admin: false
      annotations: {}
      host: foo.mbcaas.com

    serviceAccount:
      create: true
      annotations: {}
      name: ""

    nodeSelector: {}
    tolerations: []
    affinity: {}
