{{ define "mbcaas.ingress" }}
{{ $ing := . }}

{{- if $ing.ingress.enabled -}}
{{- $fullName := include "mbcaas.fullname" . -}}
{{- $svcPort := $ing.service.port -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "mbcaas.labels" . | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    external-dns.alpha.kubernetes.io/target: "ipv4.mbcaas.com"
    {{- if $ing.ingress.admin }}
    traefik.ingress.kubernetes.io/router.middlewares: kube-network-admin-basic-auth@kubernetescrd
    {{- end }}
  {{- with $ing.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: traefik
  rules:
    - host: {{ .host | quote }}
      http:
        paths:
          - path: {{ .path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
{{- end }}
{{ end }}
