{{ define "mbcaas.service" }}
{{ $svc := . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mbcaas.fullname" . }}
  labels:
    {{- include "mbcaas.labels" . | nindent 4 }}
spec:
  type: {{ $svc.service.type }}
  ports:
    - port: {{ $svc.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mbcaas.selectorLabels" . | nindent 4 }}
{{ end }}
