apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: nodepool
  labels:
    strimzi.io/cluster: {{ .Values.cluster.name }}
spec:
  replicas: {{ .Values.cluster.instance.replicas }}
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: {{ .Values.cluster.instance.storage.size | quote }}
        class: {{ .Values.cluster.instance.storage.class }}
        deleteClaim: {{ .Values.cluster.instance.storage.deleteClaim | default false }}
        kraftMetadata: shared
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.cluster.name }}
  annotations:
    strimzi.io/kraft: enabled
    strimzi.io/node-pools: enabled
spec:
  kafka:
    version: {{ .Values.cluster.version | default "3.8.0" }}
    replicas: {{ .Values.cluster.instance.replicas }}
    {{- with .Values.cluster.instance.resources }}
    resources:
      {{- . | toYaml | nindent 6 }}
    {{- end }}
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      {{- with .Values.cluster.extraListeners }}
      {{- . | toYaml | nindent 6 }}
      {{- end }}
    {{- with .Values.cluster.config }}
    config:
      {{- . | toYaml | nindent 6 }}
    {{- end }}
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: {{ .Values.cluster.instance.storage.size | quote }}
          class: {{ .Values.cluster.instance.storage.class }}
          deleteClaim: {{ .Values.cluster.instance.storage.deleteClaim | default false }}
  entityOperator:
    {{- with .Values.cluster.operatorResources.topicOperator }}
    topicOperator:
      resources:
        {{- . | toYaml | nindent 8 }}
    {{- end }}
    {{- with .Values.cluster.operatorResources.userOperator }}
    userOperator:
      resources:
        {{- . | toYaml | nindent 8 }}
    {{- else }}
    userOperator: {}
    {{- end }}
    {{- with .Values.cluster.operatorResources.tlsSidecar }}
    tlsSidecar:
      resources:
        {{- . | toYaml | nindent 8 }}
    {{- end }}

