cluster:
  name: kafka-dummy-broker
  version: 3.4.0
  instance:
    replicas: 1
    resources:
      requests:
        memory: 300Mi
        cpu: 200m
      limits:
        memory: 600Mi
        cpu: 600m
    storage:
      size: 10Gi
      class: hdd-block
  zookeeper:
    storage:
      size: 5Gi
      class: hdd-block
  config:
    offsets.topic.replication.factor: 1
    transaction.state.log.replication.factor: 1
    transaction.state.log.min.isr: 1
    default.replication.factor: 1
    min.insync.replicas: 1
    inter.broker.protocol.version: "3.4"
  extraListeners: []
  operatorResources:
    topicOperator:
      requests:
        memory: 100Mi
        cpu: 50m
      limits:
        memory: 200Mi
        cpu: 100m
    tlsSidecar:
      requests:
        memory: 100Mi
        cpu: 50m
      limits:
        memory: 200Mi
        cpu: 100m

topics:
  - name: dummy-topic
    replicas: 1
    partitions: 3
    extraConfig: {}
