cluster:
  name: test-kafka
  version: "4.0.0"

  instance:
    replicas: 1
    storage:
      size: 20Gi
      class: local-path
      deleteClaim: false
    resources:
      requests:
        memory: 500Mi
        cpu: 500m
      limits:
        memory: 1000Mi
        cpu: 1000m

  config:
    default.replication.factor: 1
    min.insync.replicas: 1

  operatorResources:
    topicOperator:
      requests:
        memory: 300Mi
        cpu: 100m
      limits:
        memory: 300Mi
        cpu: 100m
    userOperator:
      requests:
        memory: 400Mi
        cpu: 200m
      limits:
        memory: 400Mi
        cpu: 200m

  extraListeners:
    - name: kubesvc
      type: cluster-ip
      tls: false
      port: 9096

topics:
  - name: test-topic
    partitions: 5
    policy: delete
    retention: 432000000 # 5d