{{ define "mbcaas.ingress" }}
{{- $root := .root -}}
{{- $default := .default -}}
{{- $appName := .appName -}}
{{- $ing := .ingress -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-%s-ing" (include "mbcaas.fullname" (dict "appName" $appName)) ($ing.host | replace "." "-") }}
  labels:
    {{- include "mbcaas.labels" (dict "root" $root "appName" $appName) | nindent 4 }}
  annotations:
  {{- with $ing.tls }}
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: {{ . }}
  {{- else }}
    traefik.ingress.kubernetes.io/router.entrypoints: web
  {{- end }}
  {{- with $ing.annotations }}
    {{ . | toYaml | nindent 4}}
  {{- end }}
spec:
  {{- with $ing.tls }}
  tls:
    - hosts:
      - {{ $ing.host }}
      secretName: {{ $ing.host }}-cert
  {{- end }}
  rules:
    - host: {{ $ing.host | quote }}
      http:
        paths:
          {{- range $ing.paths }}
          {{- $path := . }}
          - path: {{ $path.path }}
            pathType: {{ $path.type }}
            backend:
              service:
                name: {{ printf "%s-svc" (include "mbcaas.fullname" (dict "appName" $appName)) }}
                port:
                  {{- if kindIs "string" $path.port }}
                  name: {{ $path.port }}
                  {{- else if kindIs "float64" $path.port }}
                  number: {{ $path.port }}
                  {{- end }}
          {{- end }}
{{ end }}
