{{ $root := . }}
{{ $default := .Values.default }}

{{- range .Values.deploys }}
{{- $deploy := . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mbcaas.fullname" (dict "appName" $deploy.name) }}
  labels:
    {{- include "mbcaas.labels" (dict "root" $root "appName" $deploy.name) | nindent 4 }}
spec:
  {{- if not $deploy.autoscaling }}
  replicas: {{ $deploy.replicaCount | default $default.replicaCount }}
  {{- end }}
  strategy:
    type: {{ $deploy.strategy | default $default.strategy }}
  selector:
    matchLabels:
      {{- include "mbcaas.selectorLabels" (dict "root" $root "appName" $deploy.name) | nindent 6 }}
  template:
    metadata:
      {{- with $deploy.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mbcaas.selectorLabels" (dict "root" $root "appName" $deploy.name) | nindent 8 }}
    spec:
      {{- with $deploy.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ . }}
      {{- end }}
      serviceAccountName: {{ include "mbcaas.serviceAccountName" (dict "appName" $deploy.name "serviceAccount" $deploy.serviceAccount )}}
      securityContext:
        {{- toYaml $deploy.podSecurityContext | nindent 8 }}
      containers:
        {{- $mainPod := dict -}}

        {{- $mainPod := set $mainPod "name" $deploy.name}}
        {{- $mainPod := set $mainPod "securityContext" $deploy.securityContext}}
        {{- $mainPod := set $mainPod "image" $deploy.image}}
        {{- $mainPod := set $mainPod "cmd" $deploy.cmd }}
        {{- $mainPod := set $mainPod "env" $deploy.env }}
        {{- $mainPod := set $mainPod "resources" $deploy.resources }}
        {{- $mainPod := set $mainPod "probe" $deploy.probe }}
        {{- $mainPod := set $mainPod "mount" $deploy.volumes }}


        {{- if $deploy.service }}
        {{- $portsList := list }}
        {{- range $deploy.service.ports }}
          {{- $portsList = append $portsList .port }}
        {{- end }}
        {{- $mainPod := set $mainPod "ports" $portsList }}
        {{- end }}


        {{- include "mbcaas.pod"   (dict "default" $default "pod" $mainPod) | nindent 8 }}

      {{- with $deploy.volumes }}
      {{- include "mbcaas.volumes"   (dict "volumes" .) | nindent 6 }}
      {{- end }}

      {{- with $deploy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $deploy.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $deploy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{ include "mbcaas.serviceaccount" (dict "root" $root "default" $default "appName" $deploy.name "serviceAccount" $deploy.serviceAccount)}}
---
{{- if $deploy.service }}
{{ include "mbcaas.service" (dict "root" $root "default" $default "appName" $deploy.name "service" $deploy.service)}}
{{- end }}
---
{{- if $deploy.ingress }}
{{ include "mbcaas.ingress" (dict "root" $root "default" $default "appName" $deploy.name "ingress" $deploy.ingress)}}
{{- end }}
---
{{- end }}
