{{- define "mbcaas.secrets.manifest" }}
{{- $root := .root }}
{{- $secret := .secret }}
{{- $name := .name }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  {{ with $secret.annotations }}
  annotations:
    {{ . | toYaml | nindent 4 }}
  {{- end }}
type: Opaque
{{- with $secret.data }}
data:
    {{ . | toYaml | nindent 2}}
{{- end }}
{{- with $secret.stringData }}
stringData:
    {{ . | toYaml | nindent 2}}
{{- end }}
{{- end }}

{{- $root := . }}
{{- range $name, $secret := .Values.secrets }}
{{ include "mbcaas.secrets.manifest" (dict "root" $root "name" $name "secret" $secret) }}
{{ end }}