{{ $root := . }}
{{ $default := .Values.default }}

{{- range .Values.deploys }}
{{- $deploy := . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mbcaas.fullname" $deploy }}
  labels:
    {{- include "mbcaas.labels" (dict "root" $root "appName" $deploy.name) | nindent 4 }}
spec:
  {{- if not $deploy.autoscaling }}
  replicas: {{ default $deploy.replicaCount $default.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mbcaas.selectorLabels" (dict "root" $root "appName" $deploy.name) | nindent 6 }}
  template:
    metadata:
      {{- with $deploy.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mbcaas.selectorLabels" (dict "root" $root "appName" $deploy.name) | nindent 8 }}
    spec:
      {{- with $deploy.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mbcaas.serviceAccountName" (dict "appName" $deploy.name "serviceAccount" $deploy.serviceAccount )}}
      securityContext:
        {{- toYaml $deploy.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $deploy.name }}
          securityContext:
            {{- toYaml $deploy.securityContext | nindent 12 }}
          image: "{{ $deploy.image.repository }}:{{ $deploy.image.tag }}"
          imagePullPolicy: {{ $deploy.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml (default $deploy.resources $default.resources) | nindent 12 }}
      {{- with $deploy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $deploy.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $deploy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{ include "mbcaas.serviceaccount" (dict "root" $root "default" $default "appName" $deploy.name "serviceAccount" $deploy.serviceAccount)}}
{{- end }}
