{{ define "mbcaas.serviceaccount" }}
{{- $root := .root -}}
{{- $default := .default -}}
{{- $appName := .appName -}}
{{ $sa := .serviceAccount }}

{{- if $sa.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mbcaas.serviceAccountName" (dict "appName" $appName "serviceAccount" $sa )}}
  labels:
    {{- include "mbcaas.labels" (dict "root" $root "appName" $appName) | nindent 4 }}
  {{- with $sa.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{ end }}
