{{ define "mbcaas.horizontalpodautoscaler" }}
{{ $hpa := . }}
{{- if $hpa.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "mbcaas.fullname" . }}
  labels:
    {{- include "mbcaas.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "mbcaas.fullname" . }}
  minReplicas: {{ $hpa.autoscaling.minReplicas }}
  maxReplicas: {{ $hpa.autoscaling.maxReplicas }}
  metrics:
    {{- if $hpa.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ $hpa.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if $hpa.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ $hpa.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{ end }}
